import { ethers } from "hardhat";

async function main() {
  // const ERC721 = await ethers.getContractFactory("ERC721");
  // const erc721 = await ERC721.deploy();
  const SuperMarioWorld = await ethers.getContractFactory("SuperMarioWorld");
  const superMarioWorld = await SuperMarioWorld.deploy("SuperMarioWorld", "SMW");

  await superMarioWorld.deployed();

  console.log(`SuperMarioWorld contract deployed to ${superMarioWorld.address}`);

  // url generated by Pinata service when uploading the metadata json file to ipfs
  await superMarioWorld.mint("https://ipfs.io/ipfs/QmVHZJ5pQ93J4finWxeMAF4banpuEzT45JDfxFRg9HLtyE");

  console.log("NFT successfully minted!");
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
