import { ethers } from "hardhat";

async function main() {
  const SuperMarioWorldOZ = await ethers.getContractFactory("SuperMarioWorldOZ");
  const superMarioWorldOZ = await SuperMarioWorldOZ.deploy("SuperMarioWorldOZ", "SMWOZ");

  await superMarioWorldOZ.deployed();

  console.log(`SuperMarioWorldOZ contract deployed to ${superMarioWorldOZ.address}`);

  // url generated by Pinata service when uploading the metadata json file to ipfs
  await superMarioWorldOZ.mint("https://ipfs.io/ipfs/QmYBvPsQUnavKGdLvJs6vvMTB1Bk1AGJpW51nRvhGoeX56");

  console.log("NFT successfully minted!");
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
